name: Build and release on tag created
on:
  create:
    tags:
      - '*'

jobs:
  release-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle
      - name: Add permission to gradlew
        run: chmod +x gradlew
      - name: Build jar
        run: ./gradlew clean shadowJar
      - name: Force update tag release
        if: steps.cache-releases.outputs.cache-hit != 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: "build/libs/*.jar"
          allowUpdates: true